name: Monitor Spusu Prices

on:
  schedule:
    # Run daily at 8:00 AM UTC (9:00 AM CET/10:00 AM CEST)
    - cron: '0 8 * * *'

  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run price monitoring
        run: |
          python monitor_spusu_prices.py > monitoring_output.txt 2>&1
          cat monitoring_output.txt

      - name: Check for price changes
        id: price_changes
        run: |
          if grep -q "Price changes detected:" monitoring_output.txt; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
            echo "📈 Price changes detected!"
            
            # Extract price changes from output
            grep -A 20 "Price changes detected:" monitoring_output.txt > price_changes.txt
            
            # Generate detailed Telegram message using Python script
            python3 generate_telegram_message.py price_changes.txt > telegram_message.txt
            
            cat telegram_message.txt
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
            echo "✅ No price changes detected"
          fi

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add data/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Spusu prices - $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Telegram notification
        if: steps.price_changes.outputs.changes_detected == 'true'
        run: |
          # Read the formatted message
          MESSAGE=$(cat telegram_message.txt)

          # Send to Telegram using Bot API
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{
              \"chat_id\": \"${{ secrets.TELEGRAM_CHAT_ID }}\",
              \"text\": \"$MESSAGE\",
              \"parse_mode\": \"Markdown\",
              \"disable_web_page_preview\": true
            }"

          echo "📱 Telegram notification sent!"
